### ISSUE TITLE
Download and install jpf-core : Link Dead

### ISSUE THREAD

**Issue by GermaVinsmoke** [javapathfinder/jpf-core#10]
https://github.com/javapathfinder/jpf-core/wiki/NetBeans-Plugin

Download and install [jpf-core](https://github.com/javapathfinder/jpf-core/jpf-core/index), the link is dead, can you please update it? 
If they aren't working then please delete them coz they are misleading to a 404 error page.

**Comment by vaibhavbsharma** [comment]
Thank you for pointing this issue out. I have fixed the broken link on the Netbeans-Plugin page. 

I've also moved the plugin to the github wiki repository because it may become unavailable once the nasa website is taken down. 

If you run into files being hosted at the nasa website, please report it as an issue here. It will help us migrate away from the nasa website sooner.
