### ISSUE TITLE
Formatting using `printf` broken

### ISSUE THREAD

**Issue by cyrille-artho** [javapathfinder/jpf-core#164]
Simple printf statements such as `printf("%c", 'a');` do not work at the moment, due to internal problems with formatting that cause exceptions in a native peer class.

The corresponding unit test `testPrintCharFormat` is in `src/tests/gov/nasa/jpf/test/java/io/PrintStreamTest.java`, with the failing code commented out.

It would be desirable to have a more complete unit test (with other printf options), and fixes in the model/peer classes that can support such functionality.

**Comment by IgorWilbert** [comment]
Hello @cyrille-artho! I've some skills in Java and I'd like to contribute to Pathfinder and try to participate in GSoC 2019. Is this an issue that a beginner might solve? Thanks!

**Comment by cyrille-artho** [comment]
I haven't investigated this enough, but the test is small, and the functionality is well-defined, so it seems like a reasonable issue to look at, to get familiar with JPF.
Even if you can narrow down options as where this should be fixed, that would be useful.

**Comment by IgorWilbert** [comment]
@cyrille-artho thank you, I'll see what I can do!

**Comment by manish3499** [comment]
Hello @cyrille-artho . I'm new here would like to work on this issue. I looked into some of the Standard Java class and their corresponding MJI to see what could be the problem and I have a few questions. 

Why is the PrintStream variable declared in the test class src/tests/gov/nasa/jpf/test/java/io/PrintStreamTest.java instead of making use of the "out" variable declared in the Standard Java class System and also in the Model class System? Could this be the problem?

And, all the standard classes used in the unit test do not have MJI classes in the /src/classes path. The code uses the standard libraries only, so what is the unit test's target?

Please correct me if I'm wrong. Thanks

**Comment by manish3499** [comment]
Okay. Thanks for the information, I'll look further into the issue.

**Comment by manish3499** [comment]
@cyrille-artho I've sent a PR. I think I've found the issue and have modified the code to eliminate the error.

**Comment by manish3499** [comment]
@cyrille-artho could you please close this issue if you think it's resolved?
