### ISSUE TITLE
JavaObjectInputStreamAcces cannot be resolved

### ISSUE THREAD

**Issue by durubayram** [javapathfinder/jpf-core#167]
when i run SharedSecrets.java, this error message appears on the screen. How can i fix that? Is depending on jdk version?

......................................... testing testBasic()
......................................... testBasic: Ok

......................................... testing testEnumeration()
......................................... testEnumeration: Ok

......................................... testing testOutOfBounds()
java.lang.IndexOutOfBoundsException: BitSet1024 index out of range: 2264
java.lang.IndexOutOfBoundsException: BitSet1024 index out of range: 1256
java.lang.IndexOutOfBoundsException: BitSet1024 index out of range: -1
......................................... testOutOfBounds: Ok

......................................... execution of testsuite: gov.nasa.jpf.util.BitSet1024Test SUCCEEDED
.... [1] testBasic: Ok
.... [2] testEnumeration: Ok
.... [3] testOutOfBounds: Ok
......................................... tests: 3, failures: 0, errors: 0

**Comment by cyrille-artho** [comment]
This message is the exception that is thrown by BitSet1024 when called with an index out of range. The exception is expected. The test therefore works as expected, but the lines that print the exception on stdout are bad practice.

Please look at `src/tests/gov/nasa/jpf/util/BitSet1024Test.java` and replace `System.out.println(x);` with a comment: `// expected behavior`.

This change will clean up the test log. After that, you can submit a pull request here.

I will be traveling so I may not be able to accept PRs quickly during the next week, but I'll look at them eventually.

**Comment by durubayram** [comment]
it doesn't give any error by BitSet1024. But still, jpf-core folder when it's imported, giving an error which is 
'JavaObjectInputStreamAccess cannot be resolved to a type	SharedSecrets.java	/jpf-core/src/classes/sun/mis'
when i try to run one of the examples in the src, it returns what i wanna see although proceeding with errors. How can i get rid of that error? or Should i ?

**Comment by cyrille-artho** [comment]
Which version of `javac` are you using to compile the sources? You need to use Java 8, but a somewhat recent release. If your version is (for example), `java version "1.8.0_151"` or newer, you're fine. Otherwise, you should probably upgrade to a more recent update of Java 8 (but not the full upgrade to Java 11).

**Comment by cyrille-artho** [comment]
This version should compile. It could be a Java configuration issue, as the class above is one of Sun's unofficial classes, and may not exists in certain Java versions. (But it should exist in the one you are using, so perhaps it is not found for some reason.)

**Comment by gayanW** [comment]
JavaObjectInputStreamAccess is added in u151 and removed since u161/162. It is again being added to u171. So you may try updating to u171 or newer.

**Comment by kartikey20** [comment]
I was also facing same issue. I had Jdk1.7.0.79. Then I updated it with Jdk8.0.120. Then the problem solved.
