### ISSUE TITLE
The import org.objectweb cannot be resolved

### ISSUE THREAD

**Issue by adityakapre** [javapathfinder/jpf-core#267]
I am trying to compile  the source code on linux (Ubuntu 18) with java 1.8.0_265 but I get following error

`The import org.objectweb cannot be resolved`

**Comment by cyrille-artho** [comment]
This may be a problem with gradle somehow not finding the necessary libraries.
Make sure you use the version of gradle that is provided by the wrapper: run `./gradlew` instead of just `gradle`.

If this does not help: This dependency exists only within `src/tests/gov/nasa/jpf/test/java/lang/ClassLoaderTest.java`.
If, for some reason, you cannot fix this dependency on your system, you can simply remove that class and compile/test the code without it. (Use "rm" instead of "git rm" so this change will not be reflected in any pull request.)

**Comment by adityakapre** [comment]
Thanks for your input :+1: 
I was able to build using `./gradlew` 
When I try to run using the command `<jpf-core-dir>/bin/jpf <application-property-file>.jpf` it gives me following.

```
adi@Adi:~/jpf-platform/jpf-core$ /bin/jpf HelloWorld.jpf
bash: /bin/jpf: No such file or directory
```

**Comment by adityakapre** [comment]
I see many classes moved from jvm to vm directory
I used to use following class:

`import gov.nasa.jpf.jvm.JVM;
`
But I am unable to find it in `vm` directory

**Comment by cyrille-artho** [comment]
Yes, `VM` abstracts away from the detailed bytecode representation and is the base interface now.
