### ISSUE TITLE
Check if any changes in branch `master` need to be merged into `java-10-gradle`

### ISSUE THREAD

**Issue by cyrille-artho** [javapathfinder/jpf-core#374]
Before we make the Java 11 version official, let's ensure we are not missing out on any important changes/fixes from `master`.

**Comment by cyrille-artho** [comment]
We can use the branch comparison feature in GitHub to see if some of the 1300+ deletions are things we want to keep: https://github.com/javapathfinder/jpf-core/compare/master...java-10-gradle
Most deletions are parts of changes (`-` for `master` branch, `+` for `java-10-gradle` branch), but perhaps a few were fixes that were only applied to `master`. These could also be documentation or typos in comments.
We would like that several of us review this branch comparison to ensure we don't miss anything.

**Comment by varad64** [comment]
Hello @cyrille-artho, upon thoroughly reviewing all the changes via GitHub's comparison feature, I have found that the 1,327 deletions are direct replacements, changes to ensure better compatibility and refactoring. None of the deletions made show up in the branch comparison feature.

However, when these files are compared by looking within their respective branches, there are fixes that were applied to only the `master` branch. The files which have had fixes only on the `master` branch are as follows:


- `build.gradle` : Misses fixes from #203, #285 and #296 
- `jpf.properties` : Misses fixes from #203

- **Model class:**
  1. `classes/java/lang/System.java` : Misses @cyrille-artho's fix for [Fix for System.in.available()](https://github.com/javapathfinder/jpf-core/commit/55f4f09d392d1f721119ec3382caeffcefc9a895)

- **JPF source:**
  1. `jpf/vm/ClassInfo.java` : Misses fixes from #209 
  2. `jpf/vm/MJIEnv.java` : Misses @cyrille-artho's fix - [FIX: "java.lang.Char" should be "java.lang.Character"](https://github.com/javapathfinder/jpf-core/commit/f7336c4df1322b1d586c0ebc34c10fd57f340667#diff-eeacb9e86783d227327b1d7eaa8c6fee0845fb33eda718ddaf64f8ba46112a7a)
  3. `jpf/vm/StackFrame.java` : Misses fix from #166 and #295
 

- **Native peers:**
  1. `peers/JPF_java_lang_ClassLoader.java` : Misses fixes from #203 
  2. `peers/JPF_java_lang_String.java` : Misses @cyrille-artho's fix - [Fixed out-of-bounds cases for substring](https://github.com/javapathfinder/jpf-core/commit/b592174fd5484cb641f1039a4eccc8af6e8c525f)

- **Test files:**
  1. `test/java/lang/ClassTest.java` : Misses fix from #372   
  2. `test/java/lang/ClassLoaderTest.java` : Misses fix from #203 
  3. `test/java/lang/RunTimeTest.java` : Misses @cyrille-artho's fix for [Support Runtime.halt](https://github.com/javapathfinder/jpf-core/commit/c42e4fc591a787c17954e63dbbc2cf9668c6ae39#diff-463b07b4379f5d6020f397fcdface08b98efcb483fce812a0138cb203fd63fd2) 
  4. `test/java/lang/StringTest.java` : Misses @cyrille-artho's fix [Added StringIndexOutOfBoundsException for charAt, with unit tests](https://github.com/javapathfinder/jpf-core/commit/1f2cfa01e157b4327d5ff28535710e84abdca9f3) and #197 fix
  5. `test/java/text/DecimalFormatTest.java` : Misses fix from #171
  
Out of the 217 changed files reviewed, the above 13 files have fixes that need to be incorporated into the `java-10-gradle` branch. 

Some files do exist such that, they have changed on the `master` branch but are not included by the branch comparison tool as the same file has not been modified on the `java-10-gradle` branch. For example, `jpf/vm/Types.java` file which has been updated with a fix for #204. 

I am reviewing all files to make sure we do not miss such fixes.

Thanks!

cc @pparizek

**Comment by varad64** [comment]
Hello @cyrille-artho and @pparizek, following up on my last comment about identifying files modified only on the `master` branch, so as to not skip any fixes/features before making the `java-10-gradle` the default branch. All such files have been identified after thorough investigation and there are 43 such files, please find them categorised as below:

- **Model classes: (src/classes)**
  1. `classes/java/lang/ThreadLocal.java` : Misses the update for #292
  2. `classes/java/nio/Buffer.java` : Misses the fix #171
  3. `classes/java/nio/ByteBuffer.java` : Misses the fix #171 
  4. `classes/java/text/NumberFormat.java` : Misses the fix #171
  5. `classes/java/util/regex/Matcher.java` : Misses the fix #171 
  6. `classes/java/util/regex/Pattern.java` : Misses the fix #244
  
-   **JPF source: (src/main/gov/nasa/jpf)**
    1. `jpf/jvm/bytecode/DDIV.java` : Misses @cyrille-artho's [fix](https://github.com/javapathfinder/jpf-core/commit/5cfe5f6b3052fc76ef16c15ad11a177c479c1920) for division by zero for doubles.
    2. `jpf/listener/BitFlipListener.java` : Added as part of #295 
    3. `jpf/report/Publisher.java` : Misses @cyrille-artho's [fix](https://github.com/javapathfinder/jpf-core/commit/d275f72b1878404b0b4d80a4845969d3370f0e06) to address missing code.
    4. `jpf/search/RandomSearch.java` : Misses the fix from #212 
    5. `jpf/search/Search.java` : Documentation update as part of #184 
    6. `jpf/search/SearchListener.java` : Documentation update as part of #178 
    7. `jpf/search/SearchListenerAdapter.java` : Documentation update as part of #178 
    8. `jpf/vm/serialize/PolDetSerializer.java` : Added per #285 
    9. `jpf/vm/JPF_gov_nasa_jpf_vm_Verify.java` : Updated as part of #295
    10. `jpf/vm/NativePeer.java` : Typo fixed as part of #182
    11. `jpf/vm/Types.java` : Misses the fix made for #295 
    12. `jpf/vm/Verify.java` : Code refactored per #299  and missing fix from #295 

- **Native peers: (src/peers)**
  1. `JPF_PolDetListener.java` : Added as part of #285  
  2. `JPF_java_lang_Runtime.java` : Misses @cyrille-artho's [fix](https://github.com/javapathfinder/jpf-core/commit/c42e4fc591a787c17954e63dbbc2cf9668c6ae39#diff-463b07b4379f5d6020f397fcdface08b98efcb483fce812a0138cb203fd63fd2) for "Support runtime.halt"
  3. `JPF_java_lang_reflect_Field.java` : Misses @cyrille-artho's [fix](https://github.com/javapathfinder/jpf-core/commit/f7336c4df1322b1d586c0ebc34c10fd57f340667#diff-eeacb9e86783d227327b1d7eaa8c6fee0845fb33eda718ddaf64f8ba46112a7a) to use Character instead of Char
  4. `JPF_java_util_concurrent_atomic_AtomicReference.java` : Added as part of #182 
  5. `JPF_java_util_regex_Matcher.java` : Misses the fix #171
  

- **Tests: (src/tests)**
  1. `PolDet` : Tests added as part of #285 
  2. `ThreadLocalTest` : Added as part of #292 
  3. `test/basic/ConsolePublisherTest.java` : Misses @cyrille-artho's [fix](https://github.com/javapathfinder/jpf-core/commit/d275f72b1878404b0b4d80a4845969d3370f0e06) to address missing code. Test does not exist on the `java-10-gradle` branch
  4. `test/java/concurrent/AtomicReferenceTest.java` : Added as part of #182 
  5. `test/java/io/FileIOTest.java` : Added as part of @cyrille-artho's [test on redirecting stdout to file](https://github.com/javapathfinder/jpf-core/commit/2fc7c6100c2bb7cf4452ecfd72a628d6c06e3188)
  6. `test/java/io/PrintStream.java` : Missing the fix #172. Test does not exist on the `java-10-gradle` branch
  7. `test/java/lang/FloatTest.java` : Added as part of @cyrille-artho's [fix](https://github.com/javapathfinder/jpf-core/commit/5cfe5f6b3052fc76ef16c15ad11a177c479c1920) for division by zero for doubles.
  8. `test/java/lang/DoubleTest.java` : Added as part of @cyrille-artho's [fix](https://github.com/javapathfinder/jpf-core/commit/5cfe5f6b3052fc76ef16c15ad11a177c479c1920) for division by zero for doubles.
  9. `test/java/lang/SystemTest.java` : Misses @cyrille-artho's [fix for System.in.available()](https://github.com/javapathfinder/jpf-core/commit/55f4f09d392d1f721119ec3382caeffcefc9a895)
  10. `test/java/nio/ByteBufferTest.java` : Added as part of #171 
  11. `test/java/util/CalendarTest.java` : Added as part of #181. **Not sure if this should be considered**
  12. `test/mc/basic/StatelessTest.java` : Updated as part of #212 
  13. `test/mc/data/BitFlipTest.java` : Added as part of #295 
  14. `test/vm/StackFrameTest.java` : Added as part of #166 
  15. `test/java8/functionTest/FunctionsTest.java` : Added as part of #308 
  16. `test/java8/timeTest` : Added as part of #312 
  17. `test/java8/StreamTest.java` : Added as part of #302 

- **Examples: (src/examples)**
  - `ConcurrentCount.java` and `ConcurrentCount.jpf` : Added as part of #177. **Not sure if these should be considered**

- **Annotations: (src/annotations)**
  - `annotation/BitFlip.java` : Added as part of #295. 

Thank you!

**Comment by varad64** [comment]
Hello @cyrille-artho and @pparizek, a total of 35 pull requests / commits were identified which modify the above listed files only on the master branch. The changes comprise bug fixes, addition of functionality, documentation updates and addition of a JPF example.

After going through all the 35 patches, please find the updates as below:

1. 28 patches successfully pass. Updates were necessary for some patches to work as expected.
2. 3 patches related to `Types`, `ClassLoaderTest` are on hold as #410 which modifies the same set of files and tests modified by the patches
3. 4 patches related to the `String` class and its native peer as the implementation of the `String` class has changed, and these patches are no longer relevant.

All of the details about the patches applied has been maintained [here](https://docs.google.com/spreadsheets/d/1lbqCpu21atUA7WSfSuJJ4e_MTY9fMNot6PKbrzzk5zs/edit?usp=sharing).

Thanks!

**Comment by varad64** [comment]
Hello @cyrille-artho and @pparizek, the exercise of applying patches that either add new functionality or fix bugs, from the `master` branch to the `java-10-gradle` branch is now complete.

The patches that were on hold due to #388 and 388 itself have now been included in the list and a related patch, #208 is also added. This takes the total tally of patches to 37, and of these:

1. 32 patches have been applied and successfully pass.
2. 4 patches, related to the `String` class and its native peer have been skipped as the implementation of the class has been changed. 
3. 1 [patch](https://github.com/javapathfinder/jpf-core/commit/c42e4fc591a787c17954e63dbbc2cf9668c6ae39) has been skipped as #388 redefines and adds to the former.

All details about can be found in this [spreadsheet](https://docs.google.com/spreadsheets/d/1lbqCpu21atUA7WSfSuJJ4e_MTY9fMNot6PKbrzzk5zs/edit?usp=sharing).

Thanks!

**Comment by cyrille-artho** [comment]
Great, so we can close this issue now, right?

**Comment by varad64** [comment]
Yes @cyrille-artho, good to close this issue now.
Thanks!
